service: anonyak

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handlers/hello.world
    events:
     - http:
         path: /
         method: get
  host:
    handler: handlers/host.get
    events:
     - http:
         path: /host
         method: get
  client:
    handler: handlers/client.post
    events:
     - http:
         path: /client
         method: post